### ISSUE TITLE
Komplexe Geometrien

### ISSUE THREAD

**Issue by MagnusOstertag** [NumerischeSimulation/FinalProject#3]
Mit einem Input parser matlab mit .csv ins Programm. Wenn die Dimensionen des Bildes nicht mit der `ini` Datei übereinstimmen, dann einen Fehler werfen.

**Comment by kimkroener** [comment]
- [x]  Input Geometrie erstellen
- [x] Dateiformat? csv
- [x] Bild -> Matlab -> csv -> Image

**Comment by MagnusOstertag** [comment]
Szenarien überlegen
